"""add full text search to document chunks

Revision ID: 160f4975fb02
Revises: 77baf13e30b7
Create Date: 2026-09-26 14:52:16.302725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '160f4975fb02'
down_revision: Union[str, Sequence[str], None] = '77baf13e30b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('search_vector', postgresql.TSVECTOR(),
                                               sa.Computed("to_tsvector('simple', content)", persisted=True),
                                               nullable=False))
    op.create_index('ix_document_chunks_search_vector', 'document_chunks', ['search_vector'], unique=False,
                    postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_document_chunks_search_vector', table_name='document_chunks', postgresql_using='gin')
    op.drop_column('document_chunks', 'search_vector')
    # ### end Alembic commands ###
