"""index status

Revision ID: 3b20d05671d2
Revises: a493945db50a
Create Date: 2026-10-05 14:13:37.058617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '3b20d05671d2'
down_revision: Union[str, Sequence[str], None] = 'a493945db50a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_messages', 'role',
                    existing_type=sa.VARCHAR(length=28),
                    type_=sa.Enum('USER', 'ASSISTANT', name='messagerole', native_enum=False),
                    existing_nullable=False)
    op.create_index(op.f('ix_document_chunks_embedding_status'), 'document_chunks', ['embedding_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_chunks_embedding_status'), table_name='document_chunks')
    op.alter_column('chat_messages', 'role',
                    existing_type=sa.Enum('USER', 'ASSISTANT', name='messagerole', native_enum=False),
                    type_=sa.VARCHAR(length=28),
                    existing_nullable=False)
    # ### end Alembic commands ###
