"""update model for chunking and embedding

Revision ID: 4382f28340f1
Revises: 8bc458c7d9f4
Create Date: 2026-09-17 09:42:32.154836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = '4382f28340f1'
down_revision: Union[str, Sequence[str], None] = '8bc458c7d9f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('embedding_status',
                                               sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED',
                                                       name='embeddingstatus', native_enum=False), nullable=False))
    op.add_column('document_chunks', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('document_chunks', 'embedding',
                    existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
                    nullable=True)
    op.alter_column('document_chunks', 'metadata_chunk',
                    existing_type=postgresql.JSON(astext_type=sa.Text()),
                    type_=postgresql.JSONB(astext_type=sa.Text()),
                    existing_nullable=False)
    op.drop_constraint(op.f('document_chunks_document_id_fkey'), 'document_chunks', type_='foreignkey')
    op.create_foreign_key(None, 'document_chunks', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.alter_column('documents', 'status',
                    existing_type=sa.VARCHAR(length=50),
                    type_=sa.Enum('PROCESSING', 'COMPLETED', 'FAILED', name='documentstatus', native_enum=False),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'status',
                    existing_type=sa.Enum('PROCESSING', 'COMPLETED', 'FAILED', name='documentstatus',
                                          native_enum=False),
                    type_=sa.VARCHAR(length=50),
                    existing_nullable=False)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'document_chunks', type_='foreignkey')
    op.create_foreign_key(op.f('document_chunks_document_id_fkey'), 'document_chunks', 'documents', ['document_id'],
                          ['id'])
    op.alter_column('document_chunks', 'metadata_chunk',
                    existing_type=postgresql.JSONB(astext_type=sa.Text()),
                    type_=postgresql.JSON(astext_type=sa.Text()),
                    existing_nullable=False)
    op.alter_column('document_chunks', 'embedding',
                    existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
                    nullable=False)
    op.drop_column('document_chunks', 'created_at')
    op.drop_column('document_chunks', 'embedding_status')
    # ### end Alembic commands ###
