"""downgrade vector dimension

Revision ID: 77baf13e30b7
Revises: 33530d63dfc2
Create Date: 2026-09-24 21:46:35.179571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector

# revision identifiers, used by Alembic.
revision: str = '77baf13e30b7'
down_revision: Union[str, Sequence[str], None] = '33530d63dfc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_chunks', 'embedding',
                    existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=3072),
                    type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_chunks', 'embedding',
                    existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
                    type_=pgvector.sqlalchemy.vector.VECTOR(dim=3072),
                    existing_nullable=True)
    # ### end Alembic commands ###
