"""deleting knowledgebase do not cascade deletion of documents

Revision ID: 8bc458c7d9f4
Revises: a8331e12d1b5
Create Date: 2026-09-15 14:46:06.092019

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8bc458c7d9f4'
down_revision: Union[str, Sequence[str], None] = 'a8331e12d1b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('user_id', sa.UUID(), nullable=False))
    op.alter_column('documents', 'knowledge_base_id',
                    existing_type=sa.UUID(),
                    nullable=True)
    op.drop_constraint(op.f('documents_knowledge_base_id_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'documents', 'knowledge_bases', ['knowledge_base_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'documents', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_knowledge_base_id_fkey'), 'documents', 'knowledge_bases',
                          ['knowledge_base_id'], ['id'])
    op.alter_column('documents', 'knowledge_base_id',
                    existing_type=sa.UUID(),
                    nullable=False)
    op.drop_column('documents', 'user_id')
    # ### end Alembic commands ###
