"""add default value to updatedat

Revision ID: a8331e12d1b5
Revises: be4a9f671a24
Create Date: 2026-09-15 12:44:51.432789

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'a8331e12d1b5'
down_revision: Union[str, Sequence[str], None] = 'be4a9f671a24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
